name: quiz_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  dartz: ^0.10.1
  dio: ^4.0.4
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  observable_ish: ^3.0.1
  equatable: ^2.0.5
  share_plus: ^6.3.0

  #Service
  # firebase_core: ^2.15.1
  # cloud_firestore: ^4.9.0

  #UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  syncfusion_flutter_charts: ^23.1.36

  # Stacked packages
  stacked: ^3.3.0
  stacked_hooks: ^0.2.3
  stacked_services: ^0.9.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.4
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
